"""empty message

Revision ID: 0477f641be47
Revises: 626d2c717dbd
Create Date: 2024-07-14 18:36:01.850723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0477f641be47'
down_revision = '626d2c717dbd'
branch_labels = None
depends_on = None


def upgrade():
    # Add a temporary column with a default value
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_login', sa.Boolean(), server_default='0'))
        
    # Remove the default value constraint
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('google_login', server_default=None, existing_type=sa.Boolean(), nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('google_login')

    # ### end Alembic commands ###
