"""Add nullable last_update column to Comment

Revision ID: 404d185c5168
Revises: ec388e0a12cf
Create Date: 2024-06-15 17:16:21.435935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404d185c5168'
down_revision = 'ec388e0a12cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_update', sa.DateTime(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('last_update')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('last_update')

    # ### end Alembic commands ###
