"""empty message

Revision ID: 626d2c717dbd
Revises: 404d185c5168
Create Date: 2024-07-14 18:29:12.810804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626d2c717dbd'
down_revision = '404d185c5168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
