"""guest_author ADD

Revision ID: 983cad43a38b
Revises: 930456dc8c77
Create Date: 2024-06-11 21:04:59.449773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983cad43a38b'
down_revision = '930456dc8c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_author', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('guest_author')

    # ### end Alembic commands ###
