"""empty message

Revision ID: 9a65cd082c22
Revises: 0477f641be47
Create Date: 2024-07-15 19:18:44.227509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a65cd082c22'
down_revision = '0477f641be47'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_user', sa.Boolean(), nullable=False, server_default=sa.false()))

    # Usunięcie domyślnej wartości po dodaniu kolumny
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('google_user', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_login', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('google_user')

    # ### end Alembic commands ###
