"""empty message

Revision ID: 9ff4f95cb9a9
Revises: 0df0d6ff5c94
Create Date: 2024-09-03 19:16:16.468390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff4f95cb9a9'
down_revision = '0df0d6ff5c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=800),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###
