"""empty message

Revision ID: a021a6770c26
Revises: 70ef9220bc43
Create Date: 2024-08-08 18:06:41.244529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a021a6770c26'
down_revision = '70ef9220bc43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starred', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('starred')

    op.drop_table('reaction_like_it')
    op.drop_table('reaction_hate_it')
    op.drop_table('comment_like_it')
    op.drop_table('comment_hate_it')
    op.drop_table('post_hate_it')
    op.drop_table('news_like_it')
    op.drop_table('news_hate_it')
    # ### end Alembic commands ###
